INSERT INTO assuntos (id, materia, bloco, peso, nome, hierarquia, subTree, edital) VALUES
(201, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '1 Modelagem de situações-problema por meio de equações do 1º e 2º graus e sistemas lineares.', '1', 0, 'PRF'),
(202, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '2 Noção de função.', '2', 0, 'PRF'),
(203, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '2.1 Análise gráfica.', '2.1', 202, 'PRF'),
(204, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '2.2 Funções afim, quadrática, exponencial e logarítmica.', '2.2', 202, 'PRF'),
(205, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '2.3 Aplicações.', '2.3', 202, 'PRF'),
(206, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '3 Taxas de variação de grandezas.', '3', 0, 'PRF'),
(207, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '3.1 Razão e proporção com aplicações.', '3.1', 206, 'PRF'),
(208, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '3.2 Regra de três simples e composta.', '3.2', 206, 'PRF'),
(209, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '4 Porcentagem.', '4', 0, 'PRF'),
(210, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '5 Regularidades e padrões em sequências.', '5', 0, 'PRF'),
(211, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '5.1 Sequências numéricas.', '5.1', 210, 'PRF'),
(212, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '5.2 Progressão aritmética e progressão geométrica.', '5.2', 210, 'PRF'),
(213, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '6 Noções básicas de contagem, probabilidade e estatística.', '6', 0, 'PRF'),
(214, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '7 Descrição e análise de dados.', '7', 0, 'PRF'),
(215, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '7.1 Leitura e interpretação de tabelas e gráficos apresentados em diferentes linguagens e representações.', '7.1', 214, 'PRF'),
(216, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '7.2 Cálculo de médias e análise de desvios de conjuntos de dados.', '7.2', 214, 'PRF'),
(217, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '8 Noções básicas de teoria dos conjuntos.', '8', 0, 'PRF'),
(218, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '9 Análise e interpretação de diferentes representações de figuras planas, como desenhos, mapas e plantas.', '9', 0, 'PRF'),
(219, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '9.1 Utilização de escalas.', '9.1', 218, 'PRF'),
(220, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '9.2 Visualização de figuras espaciais em diferentes posições.', '9.2', 218, 'PRF'),
(221, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '9.3 Representações bidimensionais de projeções, planificações e cortes.', '9.3', 218, 'PRF'),
(222, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '10 Métrica.', '10', 0, 'PRF'),
(223, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '10.1 Áreas e volumes.', '10.1', 222, 'PRF'),
(224, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '10.2 Estimativas.', '10.2', 222, 'PRF'),
(225, 'RACIOCÍNIO LÓGICO-MATEMÁTICO', 'I', 0, '10.3 Aplicações.', '10.3', 222, '');
